ci: update semantic release to use v20 and update husky post-merge

diff --git a/.husky/post-merge b/.husky/post-merge
--- a/.husky/post-merge
+++ b/.husky/post-merge
@@ -1,1 +1,5 @@
-pnpm
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+echo "Running post-merge hook..."
+pnpm install || echo "pnpm install failed"
